apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mongodb-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: vuha.jaxtony.xyz
    http:
      paths:
      - path: /db
        pathType: Prefix
        backend:
          service:
            name: mongodb-service
            port:
              number: 27017