apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kong-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-pod"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  tls:
  - hosts:
    - kong-demo.mb-innovationlab.com
    secretName: tls-abc-certs
  rules:
  - host: kong-demo.mb-innovationlab.com
    http:
      paths:
      - path: /db(.*)
      # - path: /
        # pathType: Prefix
        pathType: Exact
        backend:
          service:
            name: mongo-express-service
            port:
              number: 4200