apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-db
  labels: {{ include "common.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector: 
    matchLabels: {{ include "common.lables" . | nindent 6 }}
  template:
    metadata:
      lables: {{ include "common.lables" . | mindent 8 }}
    spec:
      containers:
      