apiVersion: apps/v1
kind: Deployment
metadata:
  name: { .Release.Name }
  namespace: { .Values.deploy.metadata.namespace }
  labels: {- include "common.lables" . | nindent 2}
spec:

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: { .Release.Name }
  namespace: { .Values.namespace }
spec:
  rules:
    - host: { .Values.ingress.host }
      http:
        - paths: /(.*)
          backend:

---
apiVersion: v1
kind: Service
metadata:
  name:
  namespace:
  lables: {- include "common.labels" . | nindent 2}
spec: