apiVersion: apps/v1
kind: Deployment
metadata:
spec:

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: { .Release.Name }
  namespace: { .Values.namespace }
spec:
  rules:
    - host: { .Values.ingress.host }
      http:
        - paths: /(.*)
          backend:

---
apiVersion: v1
kind: Service
metadata:
spec: