apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}db-service
spec:
  selector:
    app: {{ .Release.Name }}db
    type: {{ .Values.service.type }}
  # type: LoadBalancer default is ClusterIP
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017