apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-express-service
spec:
  selector:
    app: {{ .Release.Name }}-express
  # type: LoadBalancer # tao external ip public ra ngoai
  ports:
  - protocol: TCP
    port: {{ .Values.port }}
    targetPort: {{ .Values.port }}
    # nodePort: {{ .Values.port }}