deploy:
  metatdata:
    namespace: <namespace>

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS, DELETE"
    nginx.ingress.kubernetes.io/whitelist-source-range: 14.232.243.192,59.153.235.200,59.153.235.173
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: jenkins.jaxtony.xyz
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
   - secretName: jenkins-tls
     hosts:
       - jenkins.jaxtony.xyz

