apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  selector: {{ include "common.labels" . | indent 4 }}
  ports:
  - protocol: TCP
    port: {{ .Values.port }}
    targetPort: {{ .Values.targetPort }}