apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt-{{ .Release.Name }}
spec:
  acme:
    email: {{ .Values.admin_email }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-{{ .Release.Name }}
    solvers:
    - http01:
        ingress:
          class: nginx
      selector: {}
